name: SnowballGame
main: com.github.kanesada2.SnowballGame.SnowballGame
version: 2.0.0
api-version: 1.13
commands:
  SnowballGame:
    description: get SnowballGame's items.
    aliases: sbg
permissions:
  SnowballGame.*:
    description: Gives access to all SnowballGame commands
    default: op
    children:
      Snowballgame.config: true
      Snowballgame.get: true
      Snowballgame.please: true
      Snowballgame.msg: true
      Snowballgame.update: true
  Snowballgame.config:
    description: Allows you to reload SnowballGame's config
    default: op
  Snowballgame.get:
    description: Allows you to get SnowballGame's items
    default: op
  Snowballgame.please:
    description: Allows you to get SnowballGame's items
    default: true
  Snowballgame.sweep:
    description: Allows you to clean up floating balls around you
    default: true
  SnowballGame.msg:
    description: Allows you to enable|disable sbg's message
    default: true
  SnowballGame.update:
    description: Allows you to convert old version items in your inventory to the current format.
    default: true